---

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: types/user_parameter
  vars:
    zabbix_agent__userparameter:
      name: sssd
      userparameters:
        - key: sssd.discovery
          comment: return zabbix discovery item for sssd domains
          command: >
            /usr/bin/env python -c
            'import json, sys; json.dump({"data": list(map(lambda x: {"{"+"#SSSD_DOMAIN}": x}, {{ sssd__domains|list|to_json }} ))}, sys.stdout)'
      state: present
  tags: ['sssd', 'sssd-monitoring']
