---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['sssd', 'sssd-facts']

- name: Insert custom fact file
  copy:
    src: files/sssd.facts.py
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/sssd.fact"
    mode: 0755
  tags: ['sssd', 'sssd-facts']
