---
# tasks file for sssd

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['sssd', 'sssd-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['sssd', 'sssd-configure']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['sssd', 'sssd-service']
