---
# handlers file for sssd

- name: restart-sssd
  shell: 'rm --force {{ sssd__cache_directory }}/*'
  notify: ['restart-sssd-daemon']

- name: restart-sssd-daemon
  service:
    name: '{{ sssd__service_name }}'
    state: restarted
